#!/bin/sh

if [ "$(id -u)" != "0" ]; then
    echo "You must be root or have root priviledges in order to install this software."
    exit 1
fi

INSTALL_PATH=/opt/autotag

mkdir -p $INSTALL_PATH
cp ths $INSTALL_PATH
cp app.properties $INSTALL_PATH
cp autotag.service /usr/lib/systemd/system
systemctl start ths.service
systemctl enable ths.service
